### ISSUE TITLE
pipenv throws a TypeError exception on pipenv update command

### ISSUE THREAD

**Issue by akittas** [kennethreitz/pipenv#595]
When running `pipenv update` in any project I get an `TypeError` exception:
```
Traceback (most recent call last):
  File "C:\Programs\Python36\Scripts\pipenv-script.py", line 11, in <module>
    load_entry_point('pipenv==7.2.8', 'console_scripts', 'pipenv')()
  File "C:\Programs\Python36\lib\site-packages\pipenv\vendor\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "C:\Programs\Python36\lib\site-packages\pipenv\vendor\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "C:\Programs\Python36\lib\site-packages\pipenv\vendor\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Programs\Python36\lib\site-packages\pipenv\vendor\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Programs\Python36\lib\site-packages\pipenv\vendor\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
TypeError: update() got an unexpected keyword argument 'clear'
```
This has come up in version 7.2.8 but is working fine in version 7.2.5

**Comment by kennethreitz** [comment]
thanks, will fix

**Comment by kennethreitz** [comment]
fixed!

**Comment by kennethreitz** [comment]
released
